### ISSUE TITLE
Unpickling fails with NoSuchElementException

### ISSUE THREAD

**Issue by tutnixzursache** [benhutchison/prickle#28]
Hi @benhutchison,
i found another issue, the following code
```scala
case class SharedFoo(id: Option[String],
                     comment: Option[String],
                     asdf: Set[String])
//...
val foos = Set(SharedFoo(Some("a"),None,Set()),
      SharedFoo(Some("b"),None,Set()),
      SharedFoo(Some("c"),None,Set()),
      SharedFoo(Some("d"),None,Set()),
      SharedFoo(Some("e"),None,Set()))
val str = Pickle.intoString(foos)
val t = Unpickle[Set[SharedFoo]].fromString(str)
println(t.isSuccess)
t.failed.foreach(_.printStackTrace)
```
yields 
```
false
java.util.NoSuchElementException: key not found: 2
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
        at prickle.Unpickler$$anonfun$unpickleSeqish$1$$anonfun$apply$19$$anonfun$apply$20.apply(Unpickler.scala:182)
        at scala.util.Try$.apply(Try.scala:192)
        at prickle.Unpickler$$anonfun$unpickleSeqish$1$$anonfun$apply$19.apply(Unpickler.scala:182)
        at prickle.Unpickler$$anonfun$unpickleSeqish$1$$anonfun$apply$19.apply(Unpickler.scala:182)
        at scala.util.Success.flatMap(Try.scala:231)
        at prickle.Unpickler$$anonfun$unpickleSeqish$1.apply(Unpickler.scala:182)
        at prickle.Unpickler$$anonfun$unpickleSeqish$1.apply(Unpickler.scala:181)
        at scala.util.Try.transform(Try.scala:178)
        at prickle.Unpickler$.unpickleSeqish(Unpickler.scala:180)
        at prickle.Unpickler$$anon$9.unpickle(Unpickler.scala:235)
        at prickle.UnpickledCurry.from(Unpickler.scala:23)
...
``` 

I guess it hast something to do with the size of the outer Set because 
```scala
val foos = Set(SharedFoo(Some("a"),None,Set()),
                     SharedFoo(Some("b"),None,Set()))
```
works just fine...

Thanks for your help!

P.s.
Prickle: v1.1.9
Scala: v2.11.7
Java: v1.8.0_66

**Comment by benhutchison** [comment]
Thanks for the reproducible report. This is what I know so far:

The problem is happening because the JSON is getting mis-ordered, resulting in a `#ref` pointing at an element that hasnt yet been seen in the stream. 

Smaller working json:
"#id": "9", "#elems": [{"#id": "4", "id": {"#id": "1", "#elems": ["a"]}, "comment": **{"#id": "2", "#elems": []}**, "asdf": {"#id": "3", "#elems": []}}, {"#id": "6", "id": {"#id": "5", "#elems": ["b"]}, "comment": {"#ref": "2"}, "asdf": {"#ref": "3"}}, {"#id": "8", "id": {"#id": "7", "#elems": ["c"]}, "comment": {"#ref": "2"}, "asdf": {"#ref": "3"}}]}

Larger failing json
{"#id": "13", "#elems": [{"#id": "8", "id": {"#id": "7", "#elems": ["a"]}, "comment": **{"#ref": "2"}**, "asdf": {"#ref": "3"}}, {"#id": "10", "id": {"#id": "9", "#elems": ["e"]}, "comment": {"#ref": "2"}, "asdf": {"#ref": "3"}}, {"#id": "6", "id": {"#id": "5", "#elems": ["d"]}, "comment": {"#ref": "2"}, "asdf": {"#ref": "3"}}, {"#id": "4", "id": {"#id": "1", "#elems": ["c"]}, "comment": **{"#id": "2", "#elems": []}**, "asdf": {"#id": "3", "#elems": []}}, {"#id": "12", "id": {"#id": "11", "#elems": ["b"]}, "comment": {"#ref": "2"}, "asdf": {"#ref": "3"}}]}

I suspected this is due to `Set` iterator order being unstable. With a Set of less than size 5, scala's std lib optimizes by using a List or similar as the impl. Thats why it only happened with 5+ elements.
